// Commune mapping for Noest API - EXACT SPELLING REQUIRED
// This will be populated with the correct commune names for each wilaya

export interface CommuneMapping {
  [wilayaId: number]: string[];
}

// Temporary mapping with known working communes
// TODO: Replace with complete list provided by user
// Note: Some wilaya IDs are missing (50, 54, 56) as per Noest system
export const VALID_COMMUNES: CommuneMapping = {
  1: [
    'Adrar',
    'Tamest',
    'Reggane',
    'Inozghmir',
    'Tsabit',
    'Zaouiet Kounta',
    'Aoulef',
    'Timokten',
    'Tamentit',
    'Fenoughil',
    'Sali',
    'Akabli',
    'O Ahmed Timmi',
    'Sbaa'
  ],
  2: [
    'Chlef',
    'Tenes',
    'Benairia',
    'El Karimia',
    'Tadjna',
    'Taougrite',
    'Beni Haoua',
    'Sobha',
    'Harchoun',
    'Ouled Fares',
    'Sidi Akacha',
    'Boukadir',
    'Beni Rached',
    'Talassa',
    'Herenfa',
    'Dahra',
    'Ouled Abbes',
    'Sendjas',
    'Zeboudja',
    'Oued Sly',
    'Abou El Hassen',
    'El Marsa',
    'Chettia',
    'Sidi Abderrahmane',
    'Labiod Medjadja',
    'Oued Fodda',
    'Ouled Ben Abdelkader',
    'Bouzghaia',
    'Ain Merane',
    'Oum Drou'
  ],
  3: [
    'Laghouat',
    'Ksar El Hirane',
    'Benacer Ben Chohra',
    'Sidi Makhlouf',
    'Hassi Delaa',
    'Hassi R Mel',
    'Ain Mahdi',
    'Tadjmout',
    'Kheneg',
    'Gueltat Sidi Saad',
    'Ain Sidi Ali',
    'Beidha',
    'Brida',
    'El Ghicha',
    'Hadj Mechri',
    'Sebgag',
    'Taouiala',
    'Tadjrouna',
    'Aflou',
    'El Assafia',
    'Oued Morra',
    'Oued M Zi',
    'El Haouaita',
    'Sidi Bouzid'
  ],
  4: [
    'Oum El Bouaghi',
    'Ain Beida',
    'Ainmlila',
    'Behir Chergui',
    'El Amiria',
    'Sigus',
    'El Belala',
    'Ain Babouche',
    'Berriche',
    'Ouled Hamla',
    'Dhala',
    'Ain Kercha',
    'Hanchir Toumghani',
    'Ain Diss',
    'Fkirina',
    'Souk Naamane',
    'Zorg',
    'El Fedjoudj Boughrar',
    'Ouled Zouai',
    'Bir Chouhada',
    'Ksar Sbahi',
    'Oued Nini',
    'Meskiana',
    'Ain Fekroune',
    'Ain Zitoun',
    'Ouled Gacem',
    'El Harmilia'
  ],
  5: [
    'Batna',
    'Ghassira',
    'Maafa',
    'Merouana',
    'Seriana',
    'Menaa',
    'El Madher',
    'Tazoult',
    'Ngaous',
    'Guigba',
    'Inoughissen',
    'Ouyoun El Assafir',
    'Djerma',
    'Bitam',
    'Metkaouak',
    'Arris',
    'Kimmel',
    'Tilatou',
    'Ain Djasser',
    'Ouled Selam',
    'Tigherghar',
    'Ain Yagout',
    'Fesdis',
    'Sefiane',
    'Rahbat',
    'Tighanimine',
    'Lemsane',
    'Ksar Belezma',
    'Seggana',
    'Ichmoul',
    'Foum Toub',
    'Beni Foudhala El Hakania',
    'Oued El Ma',
    'Talkhamt',
    'Bouzina',
    'Chemora',
    'Oued Chaaba',
    'Taxlent',
    'Gosbat',
    'Ouled Aouf',
    'Boumagueur',
    'Barika',
    'Djezzar',
    'Tkout',
    'Ain Touta',
    'Hidoussa',
    'Teniet El Abed',
    'Oued Taga',
    'Ouled Fadel',
    'Timgad',
    'Ras El Aioun',
    'Chir',
    'Ouled Si Slimane',
    'Zanat El Beida',
    'Amdoukal',
    'Ouled Ammar',
    'El Hassi',
    'Lazrou',
    'Boumia',
    'Boulhilat',
    'Larbaa'
  ],
  6: [
    'Bejaia',
    'Amizour',
    'Taourirt Ighil',
    'Chelata',
    'Timzrit',
    'Souk El Thenine',
    'Mcisna',
    'Thinabdher',
    'Tichi',
    'Semaoun',
    'Tifra',
    'Ighram',
    'Amalou',
    'Ifelain Ilmathen',
    'Toudja',
    'Darguina',
    'Sidi Ayad',
    'Aokas',
    'Adekar',
    'Akbou',
    'Seddouk',
    'Tazmalt',
    'Ait Rizine',
    'Chemini',
    'Souk Oufella',
    'Taskriout',
    'Tibane',
    'Tala Hamza',
    'Barbacha',
    'Beni Ksila',
    'Ouzallaguen',
    'Sidi Aich',
    'El Kseur',
    'Melbou',
    'Akfadou',
    'Leflaye',
    'Kherrata',
    'Ait Smail',
    'Boukhelifa',
    'Tizi Nberber',
    'Beni Maouch',
    'Oued Ghir',
    'Boudjellil'
  ],
  7: [
    'Biskra',
    'Oumache',
    'Branis',
    'Chetma',
    'Besbes',
    'Sidi Okba',
    'Mchouneche',
    'Ain Naga',
    'Zeribet El Oued',
    'El Kantara',
    'El Outaya',
    'Djemorah',
    'Tolga',
    'Lioua',
    'Lichana',
    'Ourlal',
    'Mlili',
    'Foughala',
    'Bordj Ben Azzouz',
    'Meziraa',
    'Bouchagroun',
    'Mekhadma',
    'El Ghrous',
    'El Hadjab'
  ],
  8: [
    'Bechar',
    'Erg Ferradj',
    'Meridja',
    'Lahmar',
    'Mechraa Houari B',
    'Kenedsa',
    'Taghit',
    'Boukais',
    'Mogheul',
    'Abadla',
    'Beni Ounif'
  ],
  9: [
    'Blida',
    'Chebli',
    'Bouinan',
    'Oued El Alleug',
    'Ouled Yaich',
    'Chrea',
    'El Affroun',
    'Chiffa',
    'Hammam Melouane',
    'Ben Khlil',
    'Soumaa',
    'Mouzaia',
    'Souhane',
    'Meftah',
    'Ouled Selama',
    'Boufarik',
    'Larbaa',
    'Oued Djer',
    'Beni Tamou',
    'Bouarfa',
    'Beni Mered',
    'Bougara',
    'Guerrouaou',
    'Ain Romana',
    'Djebabra'
  ],
  10: [
    'Bouira',
    'El Asnam',
    'Guerrouma',
    'Souk El Khemis',
    'Kadiria',
    'Hanif',
    'Dirah',
    'Ait Laaziz',
    'Taghzout',
    'Raouraoua',
    'Mezdour',
    'Haizer',
    'Lakhdaria',
    'Maala',
    'El Hachimia',
    'Aomar',
    'Chorfa',
    'Bordj Oukhriss',
    'El Adjiba',
    'El Hakimia',
    'El Khebouzia',
    'Ahl El Ksar',
    'Bouderbala',
    'Zbarbar',
    'Ain El Hadjar',
    'Djebahia',
    'Aghbalou',
    'Taguedit',
    'Ain Turk',
    'Saharidj',
    'Dechmia',
    'Ridane',
    'Bechloul',
    'Boukram',
    'Ain Bessam',
    'Bir Ghbalou',
    'Mchedallah',
    'Sour El Ghozlane',
    'Maamora',
    'Ouled Rached',
    'Ain Laloui',
    'Hadjera Zerga',
    'Ath Mansour',
    'El Mokrani',
    'Oued El Berdi'
  ],
  11: [
    'Tamanghasset'
  ],
  12: [
    'Tebessa',
    'Bir El Ater',
    'Cheria',
    'Stah Guentis',
    'El Aouinet',
    'Lahouidjbet',
    'Safsaf El Ouesra',
    'Hammamet',
    'Bir El Mokadem',
    'El Kouif',
    'Morsott',
    'El Ogla',
    'Bir Dheheb',
    'El Ogla El Malha',
    'Gorriguer',
    'Bekkaria',
    'Boukhadra',
    'Ouenza',
    'El Ma El Biodh',
    'Oum Ali',
    'Thlidjene',
    'Ain Zerga',
    'El Meridj',
    'Boulhaf Dyr',
    'Bedjene',
    'El Mazeraa'
  ],
  13: [
    'Tlemcen',
    'Beni Mester',
    'Ain Tallout',
    'Remchi',
    'El Fehoul',
    'Sabra',
    'Ghazaouet',
    'Souani',
    'Djebala',
    'El Gor',
    'Oued Chouly',
    'Ain Fezza',
    'Ouled Mimoun',
    'Amieur',
    'Ain Youcef',
    'Zenata',
    'Beni Snous',
    'Bab El Assa',
    'Dar Yaghmouracene',
    'Fellaoucene',
    'Azails',
    'Sebbaa Chioukh',
    'Terni Beni Hediel',
    'Bensekrane',
    'Ain Nehala',
    'Hennaya',
    'Maghnia',
    'Hammam Boughrara',
    'Souahlia',
    'Msirda Fouaga',
    'Ain Fetah',
    'El Aricha',
    'Souk Thlata',
    'Sidi Abdelli',
    'Sebdou',
    'Beni Ouarsous',
    'Sidi Medjahed',
    'Beni Boussaid',
    'Marsa Ben Mhidi',
    'Nedroma',
    'Sidi Djillali',
    'Beni Bahdel',
    'El Bouihi',
    'Honaine',
    'Tianet',
    'Ouled Riyah',
    'Bouhlou',
    'Souk El Khemis',
    'Ain Ghoraba',
    'Chetouane',
    'Mansourah',
    'Beni Semiel',
    'Ain Kebira'
  ],
  14: [
    'Tiaret',
    'Medroussa',
    'Ain Bouchekif',
    'Sidi Ali Mellal',
    'Ain Zarit',
    'Ain Deheb',
    'Sidi Bakhti',
    'Medrissa',
    'Zmalet El Emir Aek',
    'Madna',
    'Sebt',
    'Mellakou',
    'Dahmouni',
    'Rahouia',
    'Mahdia',
    'Sougueur',
    'Sidi Abdelghani',
    'Ain El Hadid',
    'Ouled Djerad',
    'Naima',
    'Meghila',
    'Guertoufa',
    'Sidi Hosni',
    'Djillali Ben Amar',
    'Sebaine',
    'Tousnina',
    'Frenda',
    'Ain Kermes',
    'Ksar Chellala',
    'Rechaiga',
    'Nadorah',
    'Tagdemt',
    'Oued Lilli',
    'Mechraa Safa',
    'Hamadia',
    'Chehaima',
    'Takhemaret',
    'Sidi Abderrahmane',
    'Serghine',
    'Bougara',
    'Faidja',
    'Tidda'
  ],
  15: [
    'Tizi Ouzou',
    'Ain El Hammam',
    'Akbil',
    'Freha',
    'Souamaa',
    'Mechtrass',
    'Irdjen',
    'Timizart',
    'Makouda',
    'Draa El Mizan',
    'Tizi Ghenif',
    'Bounouh',
    'Ait Chaffaa',
    'Frikat',
    'Beni Aissi',
    'Beni Zmenzer',
    'Iferhounene',
    'Azazga',
    'Iloula Oumalou',
    'Yakouren',
    'Larba Nait Irathen',
    'Tizi Rached',
    'Zekri',
    'Ouaguenoun',
    'Ain Zaouia',
    'Mkira',
    'Ait Yahia',
    'Ait Mahmoud',
    'Maatka',
    'Ait Boumehdi',
    'Abi Youcef',
    'Beni Douala',
    'Illilten',
    'Bouzguen',
    'Ait Aggouacha',
    'Ouadhia',
    'Azzefoun',
    'Tigzirt',
    'Ait Aissa Mimoun',
    'Boghni',
    'Ifigha',
    'Ait Oumalou',
    'Tirmitine',
    'Akerrou',
    'Yatafen',
    'Beni Ziki',
    'Draa Ben Khedda',
    'Ouacif',
    'Idjeur',
    'Mekla',
    'Tizi Nthlata',
    'Beni Yenni',
    'Aghrib',
    'Iflissen',
    'Boudjima',
    'Ait Yahia Moussa',
    'Souk El Thenine',
    'Ait Khelil',
    'Sidi Naamane',
    'Iboudraren',
    'Aghni Goughran',
    'Mizrana',
    'Imsouhal',
    'Tadmait',
    'Ait Bouadou',
    'Assi Youcef',
    'Ait Toudert'
  ],
  16: [
    'Alger Centre',
    'Sidi Mhamed',
    'El Madania',
    'Hamma Anassers',
    'Bab El Oued',
    'Bologhine Ibn Ziri',
    'Casbah',
    'Oued Koriche',
    'Bir Mourad Rais',
    'El Biar',
    'Bouzareah',
    'Birkhadem',
    'El Harrach',
    'Baraki',
    'Oued Smar',
    'Bourouba',
    'Hussein Dey',
    'Kouba',
    'Bachedjerah',
    'Dar El Beida',
    'Bab Azzouar',
    'Ben Aknoun',
    'Dely Ibrahim',
    'Bains Romains',
    'Rais Hamidou',
    'Djasr Kasentina',
    'El Mouradia',
    'Hydra',
    'Mohammadia',
    'Bordj El Kiffan',
    'El Magharia',
    'Beni Messous',
    'Les Eucalyptus',
    'Birtouta',
    'Tassala El Merdja',
    'Ouled Chebel',
    'Sidi Moussa',
    'Ain Taya',
    'Bordj El Bahri',
    'Marsa',
    'Haraoua',
    'Rouiba',
    'Reghaia',
    'Ain Benian',
    'Staoueli',
    'Zeralda',
    'Mahelma',
    'Rahmania',
    'Souidania',
    'Cheraga',
    'Ouled Fayet',
    'El Achour',
    'Draria',
    'Douera',
    'Baba Hassen',
    'Khracia',
    'Saoula'
  ],
  17: [
    'Djelfa',
    'Moudjebara',
    'El Guedid',
    'Hassi Bahbah',
    'Ain Maabed',
    'Sed Rahal',
    'Feidh El Botma',
    'Birine',
    'Bouira Lahdeb',
    'Zaccar',
    'El Khemis',
    'Sidi Baizid',
    'Mliliha',
    'El Idrissia',
    'Douis',
    'Hassi El Euch',
    'Messaad',
    'Sidi Ladjel',
    'Had Sahary',
    'Guernini',
    'Selmana',
    'Ain Chouhada',
    'Dar Chouikh',
    'Charef',
    'Beni Yacoub',
    'Zaafrane',
    'Deldoul',
    'Ain El Ibel',
    'Ain Oussera',
    'Benhar',
    'Hassi Fedoul',
    'Ain Fekka',
    'Tadmit'
  ],
  18: [
    'Jijel',
    'El Aouana',
    'Ziamma Mansouriah',
    'Taher',
    'Emir Abdelkader',
    'Chekfa',
    'El Milia',
    'Sidi Maarouf',
    'Settara',
    'El Ancer',
    'Sidi Abdelaziz',
    'Kaous',
    'Djmila',
    'El Kennar Nouchfi',
    'Kemir Oued Adjoul',
    'Texena',
    'Djemaa Beni Habibi'
  ],
  19: [
    'Setif',
    'Ain El Kebira',
    'Beni Aziz',
    'Ouled Sidi Ahmed',
    'Boutaleb',
    'Ain Roua',
    'Draa Kebila',
    'Bir El Arch',
    'Beni Chebana',
    'Ouled Tebben',
    'Hamma',
    'Maaouia',
    'Ain Legraj',
    'Ain Abessa',
    'Dehamcha',
    'Babor',
    'Guidjel',
    'Ain Lahdjar',
    'Bousselam',
    'El Eulma',
    'Djemila',
    'Beni Ouartilane',
    'Rosfa',
    'Ouled Addouane',
    'Belaa',
    'Ain Arnat',
    'Amoucha',
    'Ain Oulmane',
    'Beidha Bordj',
    'Bouandas',
    'Bazer Sakhra',
    'Hammam Essokhna',
    'Mezloug',
    'Bir Haddada',
    'Serdj El Ghoul',
    'Harbil',
    'El Ouricia',
    'Tizi Nbechar',
    'Salah Bey',
    'Ain Azal',
    'Guenzet',
    'Talaifacene',
    'Bougaa',
    'Beni Fouda',
    'Tachouda',
    'Beni Mouhli',
    'Ouled Sabor',
    'Guellal',
    'Ain Sebt',
    'Hammam Guergour',
    'Ait Naoual Mezada',
    'Ksar El Abtal',
    'Beni Hocine',
    'Ait Tizi',
    'Maouklane',
    'Guelta Zerka',
    'Oued El Barad',
    'Taya',
    'El Ouldja',
    'Tella'
  ],
  20: [
    'Saida',
    'Doui Thabet',
    'Ain El Hadjar',
    'Ouled Khaled',
    'Moulay Larbi',
    'Youb',
    'Hounet',
    'Sidi Amar',
    'Sidi Boubekeur',
    'El Hassasna',
    'Maamora',
    'Ain Sekhouna',
    'Ouled Brahim',
    'Tircine',
    'Ain Soltane'
  ],
  21: [
    'Skikda',
    'El Hadaik',
    'Azzaba',
    'Djendel Saadi Mohamed',
    'Ain Cherchar',
    'Bekkouche Lakhdar',
    'Es Sebt',
    'Collo',
    'Kerkera',
    'El Harrouch',
    'Zerdazas',
    'Sidi Mezghiche',
    'Emdjez Edchich',
    'Beni Oulbane',
    'Ramdane Djamel',
    'Beni Bachir',
    'Salah Bouchaour',
    'Tamalous',
    'Ain Kechra',
    'Oum Toub',
    'Bein El Ouiden',
    'Fil Fila',
    'Cheraia',
    'El Ghedir',
    'Bouchtata',
    'Hamadi Krouma'
  ],
  22: [
    'Sidi Bel Abbes',
    'Tessala',
    'Sidi Brahim',
    'Mostefa Ben Brahim',
    'Telagh',
    'Mezaourou',
    'Boukhanafis',
    'Sidi Ali Boussidi',
    'Badredine El Mokrani',
    'Amarnas',
    'Tilmouni',
    'Sidi Lahcene',
    'Ain Thrid',
    'Makedra',
    'Tenira',
    'Moulay Slissen',
    'El Hacaiba',
    'Hassi Zehana',
    'Tabia',
    'Merine',
    'Ras El Ma',
    'Ain Tindamine',
    'Ain Kada',
    'Mcid',
    'Sidi Khaled',
    'Ain El Berd',
    'Sfissef',
    'Ain Adden',
    'Oued Taourira',
    'Dhaya',
    'Zerouala',
    'Lamtar',
    'Sidi Chaib',
    'Sidi Dahou Dezairs',
    'Oued Sbaa',
    'Boudjebaa El Bordj',
    'Sehala Thaoura',
    'Sidi Yacoub',
    'Sidi Hamadouche',
    'Belarbi',
    'Oued Sefioun',
    'Teghalimet',
    'Ben Badis',
    'Sidi Ali Benyoub',
    'Chetouane Belaila',
    'Bir El Hammam',
    'Taoudmout',
    'Redjem Demouche',
    'Benachiba Chelia',
    'Hassi Dahou'
  ],
  23: [
    'Annaba',
    'Berrahel',
    'El Hadjar',
    'Eulma',
    'El Bouni',
    'Oued El Aneb',
    'Cheurfa',
    'Seraidi',
    'Ain Berda',
    'Chetaibi',
    'Sidi Amer',
    'Treat'
  ],
  24: [
    'Guelma',
    'Nechmaya',
    'Bouati Mahmoud',
    'Oued Zenati',
    'Tamlouka',
    'Oued Fragha',
    'Ain Sandel',
    'Ras El Agba',
    'Dahouara',
    'Belkhir',
    'Ben Djarah',
    'Bou Hamdane',
    'Ain Makhlouf',
    'Ain Ben Beida',
    'Khezara',
    'Beni Mezline',
    'Bou Hachana',
    'Guelaat Bou Sbaa',
    'Hammam Maskhoutine',
    'El Fedjoudj',
    'Bordj Sabat',
    'Hamman Nbail',
    'Medjez Amar',
    'Bouchegouf',
    'Heliopolis',
    'Ain Hessania',
    'Roknia',
    'Salaoua Announa',
    'Medjez Sfa',
    'Boumahra Ahmed',
    'Ain Reggada',
    'Oued Cheham',
    'Djeballah Khemissi'
  ],
  25: [
    'Constantine',
    'Hamma Bouziane',
    'El Haria',
    'Zighoud Youcef',
    'Didouche Mourad',
    'El Khroub',
    'Ain Abid',
    'Beni Hamiden',
    'Ouled Rahmoune',
    'Ain Smara',
    'Mesaoud Boudjeriou',
    'Ibn Ziad'
  ],
  26: [
    'Medea',
    'Ouzera',
    'Ouled Maaref',
    'Ain Boucif',
    'Aissaouia',
    'Ouled Deide',
    'El Omaria',
    'Derrag',
    'El Guelbelkebir',
    'Bouaiche',
    'Mezerena',
    'Ouled Brahim',
    'Damiat',
    'Sidi Ziane',
    'Tamesguida',
    'El Hamdania',
    'Kef Lakhdar',
    'Chelalet El Adhaoura',
    'Bouskene',
    'Rebaia',
    'Bouchrahil',
    'Ouled Hellal',
    'Tafraout',
    'Baata',
    'Boghar',
    'Sidi Naamane',
    'Ouled Bouachra',
    'Sidi Zahar',
    'Oued Harbil',
    'Benchicao',
    'Sidi Damed',
    'Aziz',
    'Souagui',
    'Zoubiria',
    'Ksar El Boukhari',
    'El Azizia',
    'Djouab',
    'Chahbounia',
    'Meghraoua',
    'Cheniguel',
    'Ain Ouksir',
    'Oum El Djalil',
    'Ouamri',
    'Si Mahdjoub',
    'Tlatet Eddoair',
    'Beni Slimane',
    'Berrouaghia',
    'Seghouane',
    'Meftaha',
    'Mihoub',
    'Boughezoul',
    'Tablat',
    'Deux Bassins',
    'Draa Essamar',
    'Sidi Errabia',
    'Bir Ben Laabed',
    'El Ouinet',
    'Ouled Antar',
    'Bouaichoune',
    'Hannacha',
    'Sedraia',
    'Medjebar',
    'Khams Djouamaa',
    'Saneg'
  ],
  27: [
    'Mostaganem',
    'Sayada',
    'Fornaka',
    'Stidia',
    'Ain Nouissy',
    'Hassi Maameche',
    'Ain Tadles',
    'Sour',
    'Oued El Kheir',
    'Sidi Bellater',
    'Kheiredine',
    'Sidi Ali',
    'Abdelmalek Ramdane',
    'Hadjadj',
    'Nekmaria',
    'Sidi Lakhdar',
    'Achaacha',
    'Khadra',
    'Bouguirat',
    'Sirat',
    'Ain Sidi Cherif',
    'Mesra',
    'Mansourah',
    'Souaflia',
    'Ouled Boughalem',
    'Ouled Maallah',
    'Mezghrane',
    'Ain Boudinar',
    'Tazgait',
    'Safsaf',
    'Touahria',
    'El Hassiane'
  ],
  28: [
    'Msila',
    'Maadid',
    'Hammam Dhalaa',
    'Ouled Derradj',
    'Tarmount',
    'Mtarfa',
    'Khoubana',
    'Mcif',
    'Chellal',
    'Ouled Madhi',
    'Magra',
    'Berhoum',
    'Ain Khadra',
    'Ouled Addi Guebala',
    'Belaiba',
    'Sidi Aissa',
    'Ain El Hadjel',
    'Sidi Hadjeres',
    'Ouanougha',
    'Bou Saada',
    'Ouled Sidi Brahim',
    'Sidi Ameur',
    'Tamsa',
    'Ben Srour',
    'Ouled Slimane',
    'El Houamed',
    'El Hamel',
    'Ouled Mansour',
    'Maarif',
    'Dehahna',
    'Bouti Sayah',
    'Khettouti Sed Djir',
    'Zarzour',
    'Oued Chair',
    'Benzouh',
    'Bir Foda',
    'Sidi Mhamed',
    'Ouled Atia',
    'Souamaa',
    'Ain El Melh',
    'Medjedel',
    'Slim',
    'Ain Errich',
    'Beni Ilmane',
    'Oultene',
    'Djebel Messaad'
  ],
  29: [
    'Mascara',
    'Bou Hanifia',
    'Tizi',
    'Hacine',
    'Maoussa',
    'Teghennif',
    'El Hachem',
    'Sidi Kada',
    'Zelmata',
    'Oued El Abtal',
    'Ain Ferah',
    'Ghriss',
    'Froha',
    'Matemore',
    'Makdha',
    'Sidi Boussaid',
    'El Bordj',
    'Ain Fekan',
    'Benian',
    'Khalouia',
    'El Menaouer',
    'Oued Taria',
    'Aouf',
    'Ain Fares',
    'Ain Frass',
    'Sig',
    'Oggaz',
    'Alaimia',
    'Zahana',
    'Mohammadia',
    'Sidi Abdelmoumene',
    'Ferraguig',
    'El Ghomri',
    'Sedjerara',
    'Moctadouz',
    'Bou Henni',
    'Guettena',
    'El Mamounia',
    'El Keurt',
    'Gharrous',
    'Gherdjoum',
    'Chorfa',
    'Ras Ain Amirouche',
    'Nesmot',
    'Sidi Abdeldjebar',
    'Sehailia'
  ],
  30: [
    'Ouargla',
    'Ain Beida',
    'Ngoussa',
    'Hassi Messaoud',
    'Rouissat',
    'Sidi Khouiled',
    'Hassi Ben Abdellah'
  ],
  31: [
    'Oran',
    'Gdyel',
    'Bir El Djir',
    'Hassi Bounif',
    'Es Senia',
    'Arzew',
    'Bethioua',
    'Marsat El Hadjadj',
    'Ain Turk',
    'El Ancar',
    'Oued Tlelat',
    'Tafraoui',
    'Sidi Chami',
    'Boufatis',
    'Mers El Kebir',
    'Bousfer',
    'El Karma',
    'El Braya',
    'Hassi Ben Okba',
    'Ben Freha',
    'Hassi Mefsoukh',
    'Sidi Ben Yabka',
    'Messerghin',
    'Boutlelis',
    'Ain Kerma',
    'Ain Biya'
  ],
  32: [
    'El Bayadh',
    'Rogassa',
    'Stitten',
    'Brezina',
    'Ghassoul',
    'Boualem',
    'El Abiodh Sidi Cheikh',
    'Ain El Orak',
    'Arbaouat',
    'Bougtoub',
    'El Kheither',
    'Kef El Ahmar',
    'Boussemghoun',
    'Chellala',
    'Krakda',
    'El Bnoud',
    'Cheguig',
    'Sidi Ameur',
    'El Mehara',
    'Tousmouline',
    'Sidi Slimane',
    'Sidi Tifour'
  ],
  33: [
    'Illizi'
  ],
  34: [
    'Bordj Bou Arreridj',
    'Ras El Oued',
    'Bordj Zemoura',
    'Mansoura',
    'El Mhir',
    'Ben Daoud',
    'El Achir',
    'Ain Taghrout',
    'Bordj Ghdir',
    'Sidi Embarek',
    'El Hamadia',
    'Belimour',
    'Medjana',
    'Teniet En Nasr',
    'Ouled Brahem',
    'Ouled Dahmane',
    'Hasnaoua',
    'Khelil',
    'Taglait',
    'Ksour',
    'Ouled Sidi Brahim',
    'Tixter',
    'El Ach',
    'El Anseur',
    'Tesmart',
    'Ain Tesra',
    'Bir Kasdali',
    'Ghilassa',
    'Rabta',
    'Haraza'
  ],
  35: [
    'Boumerdes',
    'Boudouaou',
    'Afir',
    'Bordj Menaiel',
    'Baghlia',
    'Sidi Daoud',
    'Naciria',
    'Djinet',
    'Isser',
    'Zemmouri',
    'Si Mustapha',
    'Tidjelabine',
    'Chabet El Ameur',
    'Thenia',
    'Timezrit',
    'Corso',
    'Ouled Moussa',
    'Larbatache',
    'Bouzegza Keddara',
    'Taourga',
    'Ouled Aissa',
    'Ben Choud',
    'Dellys',
    'Ammal',
    'Beni Amrane',
    'Souk El Had',
    'Boudouaou El Bahri',
    'Ouled Hedadj',
    'Laghata',
    'Hammedi',
    'Khemis El Khechna',
    'El Kharrouba'
  ],
  36: [
    'El Tarf',
    'Bouhadjar',
    'Ben Mhidi',
    'Bougous',
    'El Kala',
    'Ain El Assel',
    'El Aioun',
    'Bouteldja',
    'Berrihane',
    'Lac Des Oiseaux',
    'Chefia',
    'Drean',
    'Chihani',
    'Chebaita Mokhtar',
    'Asfour',
    'Echatt',
    'Zerizer',
    'Zitouna',
    'Ain Kerma',
    'Oued Zitoun',
    'Hammam Beni Salah',
    'Raml Souk'
  ],
  37: [
    'Tindouf',
    'Oum El Assel'
  ],
  38: [
    'Tissemsilt',
    'Bordj Bou Naama',
    'Theniet El Had',
    'Lazharia',
    'Beni Chaib',
    'Lardjem',
    'Melaab',
    'Sidi Lantri',
    'Bordj El Emir Abdelkader',
    'Layoune',
    'Khemisti',
    'Ouled Bessem',
    'Ammari',
    'Youssoufia',
    'Sidi Boutouchent',
    'Larbaa',
    'Maasem',
    'Sidi Abed',
    'Tamalaht',
    'Sidi Slimane',
    'Boucaid',
    'Beni Lahcene'
  ],
  39: [
    'El Oued',
    'Robbah',
    'Oued El Alenda',
    'Bayadha',
    'Nakhla',
    'Guemar',
    'Kouinine',
    'Reguiba',
    'Hamraia',
    'Taghzout',
    'Debila',
    'Hassani Abdelkrim',
    'Hassi Khelifa',
    'Taleb Larbi',
    'Douar El Ma',
    'Sidi Aoun',
    'Trifaoui',
    'Magrane',
    'Beni Guecha',
    'Ourmas',
    'El Ogla',
    'Mih Ouansa'
  ],
  40: [
    'Khenchela',
    'Mtoussa',
    'Kais',
    'Baghai',
    'El Hamma',
    'Ain Touila',
    'Taouzianat',
    'Bouhmama',
    'Remila',
    'Cherchar',
    'Babar',
    'Ensigha',
    'Ouled Rechache',
    'El Mahmal',
    'Yabous',
    'Chelia'
  ],
  41: [
    'Souk Ahras',
    'Sedrata',
    'Hanancha',
    'Mechroha',
    'Ouled Driss',
    'Tiffech',
    'Zaarouria',
    'Taoura',
    'Drea',
    'Haddada',
    'Khedara',
    'Merahna',
    'Ouled Moumen',
    'Bir Bouhouche',
    'Mdaourouche',
    'Oum El Adhaim',
    'Ain Zana',
    'Ain Soltane',
    'Quillen',
    'Sidi Fredj',
    'Safel El Ouiden',
    'Ragouba',
    'Khemissa',
    'Oued Keberit',
    'Terraguelt',
    'Zouabi'
  ],
  42: [ // Tipaza - COMPLETED
    'Tipaza',
    'Menaceur',
    'Larhat',
    'Douaouda',
    'Bourkika',
    'Khemisti',
    'Aghabal',
    'Hadjout',
    'Sidi Amar',
    'Gouraya',
    'Nodor',
    'Chaiba',
    'Ain Tagourait',
    'Cherchel',
    'Damous',
    'Meurad',
    'Fouka',
    'Bou Ismail',
    'Ahmer El Ain',
    'Bou Haroun',
    'Sidi Ghiles',
    'Messelmoun',
    'Sidi Rached',
    'Kolea',
    'Attatba',
    'Sidi Semiane',
    'Beni Milleuk',
    'Hadjerat Ennous'
  ],
  43: [ // Mila - COMPLETED
    'Mila',
    'Ferdjioua',
    'Chelghoum Laid',
    'Oued Athmenia',
    'Ain Mellouk',
    'Telerghma',
    'Oued Seguen',
    'Tadjenanet',
    'Benyahia Abderrahmane',
    'Oued Endja',
    'Ahmed Rachedi',
    'Ouled Khalouf',
    'Tiberguent',
    'Rouached',
    'Grarem Gouga',
    'Sidi Merouane',
    'Derradji Bousselah',
    'Amira Arras',
    'Terrai Bainen',
    'Hamala',
    'Ain Tine',
    'El Mechira',
    'Sidi Khelifa',
    'Zeghaia',
    'Elayadi Barbes',
    'Ain Beida Harriche',
    'Yahia Beniguecha',
    'Chigara'
  ],
  44: [ // Aïn Defla - COMPLETED
    'Ain Defla',
    'Miliana',
    'Boumedfaa',
    'Khemis Miliana',
    'Hammam Righa',
    'Arib',
    'Djelida',
    'El Amra',
    'Bourached',
    'El Attaf',
    'El Abadia',
    'Djendel',
    'Oued Chorfa',
    'Ain Lechiakh',
    'Oued Djemaa',
    'Rouina',
    'Zeddine',
    'El Hassania',
    'Bir Ouled Khelifa',
    'Ain Soltane',
    'Tarik Ibn Ziad',
    'Bordj Emir Khaled',
    'Ain Torki',
    'Sidi Lakhdar',
    'Ben Allal',
    'Ain Benian',
    'Hoceinia',
    'Barbouche',
    'Djemaa Ouled Chikh',
    'Mekhatria',
    'Bathia',
    'Tachta Zegagha',
    'Ain Bouyahia',
    'El Maine',
    'Tiberkanine',
    'Belaas'
  ],
  45: [ // Naâma - COMPLETED
    'Naama',
    'Mechria',
    'Ain Sefra',
    'Tiout',
    'Sfissifa',
    'Moghrar',
    'Assela',
    'Djeniane Bourzeg',
    'Ain Ben Khelil',
    'Makman Ben Amer',
    'Kasdir',
    'El Biod'
  ],
  46: [ // Aïn Témouchent - COMPLETED
    'Ain Temouchent',
    'Chaabet El Ham',
    'Ain Kihal',
    'Hammam Bouhadjar',
    'Bou Zedjar',
    'Oued Berkeche',
    'Aghlal',
    'Terga',
    'Ain El Arbaa',
    'Tamzoura',
    'Chentouf',
    'Sidi Ben Adda',
    'Aoubellil',
    'El Malah',
    'Sidi Boumediene',
    'Oued Sabah',
    'Ouled Boudjemaa',
    'Ain Tolba',
    'El Amria',
    'Hassi El Ghella',
    'Hassasna',
    'Ouled Kihal',
    'Beni Saf',
    'Sidi Safi',
    'Oulhaca El Gheraba',
    'Tadmaya',
    'El Emir Abdelkader',
    'El Messaid'
  ],
  47: [ // Ghardaïa - COMPLETED
    'Ghardaia',
    'Dhayet Bendhahoua',
    'Berriane',
    'Metlili',
    'El Guerrara',
    'El Atteuf',
    'Zelfana',
    'Bounoura'
  ],
  48: [ // Relizane - COMPLETED
    'Relizane',
    'Oued Rhiou',
    'Belaassel Bouzegza',
    'Sidi Saada',
    'Ouled Aiche',
    'Sidi Lazreg',
    'El Hamadna',
    'Sidi Mhamed Ben Ali',
    'Mediouna',
    'Sidi Khettab',
    'Ammi Moussa',
    'Zemmoura',
    'Beni Dergoun',
    'Djidiouia',
    'El Guettar',
    'Hamri',
    'El Matmar',
    'Sidi Mhamed Ben Aouda',
    'Ain Tarek',
    'Oued Essalem',
    'Ouarizane',
    'Mazouna',
    'Kalaa',
    'Ain Rahma',
    'Yellel',
    'Oued El Djemaa',
    'Ramka',
    'Mendes',
    'Lahlef',
    'Beni Zentis',
    'Souk El Haad',
    'Dar Ben Abdellah',
    'El Hassi',
    'Had Echkalla',
    'Bendaoud',
    'El Ouldja',
    'Merdja Sidi Abed',
    'Ouled Sidi Mihoub'
  ],
  49: [ // Timimoun - COMPLETED
    'Timimoun',
    'Charouine',
    'Ouled Said',
    'Ksar Kaddour',
    'Tinerkouk',
    'Deldoul',
    'Aougrout'
  ],
  51: [ // Ouled Djellal - COMPLETED
    'Ouled Djellal',
    'Chaiba',
    'Doucen',
    'Besbes',
    'Ras El Miad',
    'Sidi Khaled'
  ],
  52: [ // Beni Abbes - COMPLETED
    'Beni Abbes',
    'Ksabi',
    'Ouled-Khodeir',
    'Tamtert',
    'Igli',
    'El Ouata',
    'Beni-Ikhlef',
    'Kerzaz',
    'Timoudi'
  ],
  53: [ // In Salah - COMPLETED
    'Ain Salah',
    'Inghar',
    'Foggaret Ezzoua'
  ],
  55: [ // Touggourt - COMPLETED
    'Touggourt',
    'Nezla',
    'Tebesbest',
    'Zaouia El Abidia',
    'El Alia',
    'El-Hadjira',
    'Benaceur',
    'M\'naguer',
    'Taibet',
    'Blidet Amor',
    'Temacine',
    'Megarine',
    'Sidi Slimane'
  ],
  57: [ // El M'Ghair - COMPLETED
    'El M\'Ghair',
    'Oum Touyour',
    'Sidi Khelil',
    'Still',
    'Djamaa',
    'M\'rara',
    'Sidi Amrane',
    'Tenedla'
  ],
  58: [ // El Meniaa - COMPLETED
    'El Meniaa',
    'Hassi Gara',
    'Hassi Fehal'
  ]
};

// Valid wilaya IDs as per Noest system
export const VALID_WILAYA_IDS = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
  21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 55, 57, 58
];

// Helper function to validate commune for a given wilaya
export const isValidCommune = (wilayaId: number, commune: string): boolean => {
  if (!VALID_WILAYA_IDS.includes(wilayaId)) {
    console.warn(`Invalid wilaya ID: ${wilayaId}. Valid IDs: ${VALID_WILAYA_IDS.join(', ')}`);
    return false;
  }
  
  const validCommunes = VALID_COMMUNES[wilayaId];
  if (!validCommunes || validCommunes.length === 0) {
    console.warn(`No commune list available for wilaya ${wilayaId}`);
    return true; // Allow if we don't have the list yet
  }
  return validCommunes.includes(commune);
};

// Helper function to get valid communes for a wilaya
export const getValidCommunes = (wilayaId: number): string[] => {
  return VALID_COMMUNES[wilayaId] || [];
};

// Helper function to suggest the closest matching commune
export const suggestCommune = (wilayaId: number, userInput: string): string | null => {
  const validCommunes = VALID_COMMUNES[wilayaId];
  if (!validCommunes || validCommunes.length === 0) return null;
  
  const input = userInput.toLowerCase().trim();
  
  // Exact match (case insensitive)
  const exactMatch = validCommunes.find(commune => 
    commune.toLowerCase() === input
  );
  if (exactMatch) return exactMatch;
  
  // Partial match
  const partialMatch = validCommunes.find(commune =>
    commune.toLowerCase().includes(input) || input.includes(commune.toLowerCase())
  );
  if (partialMatch) return partialMatch;
  
  return null;
};

// Default commune mapping for fallback (only for wilayas we have confirmed)
export const DEFAULT_COMMUNE_BY_WILAYA: { [wilayaId: number]: string } = {
  1: 'Adrar', // Default for Adrar wilaya
  2: 'Chlef', // Default for Chlef wilaya
  3: 'Laghouat', // Default for Laghouat wilaya
  4: 'Oum El Bouaghi', // Default for Oum El Bouaghi wilaya
  5: 'Batna', // Default for Batna wilaya
  6: 'Bejaia', // Default for Béjaïa wilaya
  7: 'Biskra', // Default for Biskra wilaya
  8: 'Bechar', // Default for Béchar wilaya
  9: 'Blida', // Default for Blida wilaya
  10: 'Bouira', // Default for Bouira wilaya
  11: 'Tamanghasset', // Default for Tamanrasset wilaya
  12: 'Tebessa', // Default for Tébessa wilaya
  13: 'Tlemcen', // Default for Tlemcen wilaya
  14: 'Tiaret', // Default for Tiaret wilaya
  15: 'Tizi Ouzou', // Default for Tizi Ouzou wilaya
  16: 'Alger Centre', // Known working default for Alger
  17: 'Djelfa', // Default for Djelfa wilaya
  18: 'Jijel', // Default for Jijel wilaya
  19: 'Setif', // Default for Sétif wilaya
  20: 'Saida', // Default for Saïda wilaya
  21: 'Skikda', // Default for Skikda wilaya
  22: 'Sidi Bel Abbes', // Default for Sidi Bel Abbès wilaya
  23: 'Annaba', // Default for Annaba wilaya
  24: 'Guelma', // Default for Guelma wilaya
  25: 'Constantine', // Default for Constantine wilaya
  26: 'Medea', // Default for Médéa wilaya
  27: 'Mostaganem', // Default for Mostaganem wilaya
  28: 'Msila', // Default for M'Sila wilaya
  29: 'Mascara', // Default for Mascara wilaya
  30: 'Ouargla', // Default for Ouargla wilaya
  31: 'Oran', // Default for Oran wilaya
  32: 'El Bayadh', // Default for El Bayadh wilaya
  33: 'Illizi', // Default for Illizi wilaya
  34: 'Bordj Bou Arreridj', // Default for Bordj Bou Arreridj wilaya
  35: 'Boumerdes', // Default for Boumerdès wilaya
  36: 'El Tarf', // Default for El Tarf wilaya
  37: 'Tindouf', // Default for Tindouf wilaya - COMPLETED
  38: 'Tissemsilt', // Default for Tissemsilt wilaya - COMPLETED
  39: 'El Oued', // Default for El Oued wilaya - COMPLETED
  40: 'Khenchela', // Default for Khenchela wilaya - COMPLETED
  41: 'Souk Ahras', // Default for Souk Ahras wilaya - COMPLETED
  42: 'Tipaza', // Default for Tipaza wilaya - COMPLETED
  43: 'Mila', // Default for Mila wilaya - COMPLETED
  44: 'Ain Defla', // Default for Aïn Defla wilaya - COMPLETED
  45: 'Naama', // Default for Naâma wilaya - COMPLETED
  46: 'Ain Temouchent', // Default for Aïn Témouchent wilaya - COMPLETED
  47: 'Ghardaïa', // Default for Ghardaïa wilaya - COMPLETED
  48: 'Relizane', // Default for Relizane wilaya - COMPLETED
  49: 'Timimoun', // Default for Timimoun wilaya - COMPLETED
  51: 'Ouled Djellal', // Default for Ouled Djellal wilaya - COMPLETED
  52: 'Beni Abbes', // Default for Beni Abbes wilaya - COMPLETED
  53: 'Ain Salah', // Default for In Salah wilaya - COMPLETED
  55: 'Touggourt', // Default for Touggourt wilaya - COMPLETED
  57: 'El M\'Ghair', // Default for El M'Ghair wilaya - COMPLETED
  58: 'El Meniaa', // Default for El Meniaa wilaya - COMPLETED
};

export const getDefaultCommune = (wilayaId: number): string => {
  return DEFAULT_COMMUNE_BY_WILAYA[wilayaId] || 'Centre';
};
