export const wilayasData = [
  { code: "1", name: "Adrar", communes: ["Commune1", "Commune2"] },
  { code: "2", name: "Chlef", communes: ["Commune1", "Commune2"] },
  { code: "3", name: "Laghouat", communes: ["Commune1", "Commune2"] },
  { code: "4", name: "Oum El Bouaghi", communes: ["Commune1", "Commune2"] },
  { code: "5", name: "Batna", communes: ["Commune1", "Commune2"] },
  { code: "6", name: "Béjaïa", communes: ["Commune1", "Commune2"] },
  { code: "7", name: "Biskra", communes: ["Commune1", "Commune2"] },
  { code: "8", name: "Béchar", communes: ["Commune1", "Commune2"] },
  { code: "9", name: "Blida", communes: ["Commune1", "Commune2"] },
  { code: "10", name: "Bouira", communes: ["Commune1", "Commune2"] },
  { code: "11", name: "Tamanrasset", communes: ["Commune1", "Commune2"] },
  { code: "12", name: "Tébessa", communes: ["Commune1", "Commune2"] },
  { code: "13", name: "Tlemcen", communes: ["Commune1", "Commune2"] },
  { code: "14", name: "Tiaret", communes: ["Commune1", "Commune2"] },
  { code: "15", name: "Tizi Ouzou", communes: ["Commune1", "Commune2"] },
  { code: "16", name: "Algiers", communes: ["Commune1", "Commune2"] },
  { code: "17", name: "Djelfa", communes: ["Commune1", "Commune2"] },
  { code: "18", name: "Jijel", communes: ["Commune1", "Commune2"] },
  { code: "19", name: "Sétif", communes: ["Commune1", "Commune2"] },
  { code: "20", name: "Saïda", communes: ["Commune1", "Commune2"] },
  { code: "21", name: "Skikda", communes: ["Commune1", "Commune2"] },
  { code: "22", name: "Sidi Bel Abbès", communes: ["Commune1", "Commune2"] },
  { code: "23", name: "Annaba", communes: ["Commune1", "Commune2"] },
  { code: "24", name: "Guelma", communes: ["Commune1", "Commune2"] },
  { code: "25", name: "Constantine", communes: ["Commune1", "Commune2"] },
  { code: "26", name: "Médéa", communes: ["Commune1", "Commune2"] },
  { code: "27", name: "Mostaganem", communes: ["Commune1", "Commune2"] },
  { code: "28", name: "M'Sila", communes: ["Commune1", "Commune2"] },
  { code: "29", name: "Mascara", communes: ["Commune1", "Commune2"] },
  { code: "30", name: "Ouargla", communes: ["Commune1", "Commune2"] },
  { code: "31", name: "Oran", communes: ["Commune1", "Commune2"] },
  { code: "32", name: "El Bayadh", communes: ["Commune1", "Commune2"] },
  { code: "33", name: "Illizi", communes: ["Commune1", "Commune2"] },
  { code: "34", name: "Bordj Bou Arréridj", communes: ["Commune1", "Commune2"] },
  { code: "35", name: "Boumerdès", communes: ["Commune1", "Commune2"] },
  { code: "36", name: "El Tarf", communes: ["Commune1", "Commune2"] },
  { code: "37", name: "Tindouf", communes: ["Commune1", "Commune2"] },
  { code: "38", name: "Tissemsilt", communes: ["Commune1", "Commune2"] },
  { code: "39", name: "El Oued", communes: ["Commune1", "Commune2"] },
  { code: "40", name: "Khenchela", communes: ["Commune1", "Commune2"] },
  { code: "41", name: "Souk Ahras", communes: ["Commune1", "Commune2"] },
  { code: "42", name: "Tipaza", communes: ["Commune1", "Commune2"] },
  { code: "43", name: "Mila", communes: ["Commune1", "Commune2"] },
  { code: "44", name: "Aïn Defla", communes: ["Commune1", "Commune2"] },
  { code: "45", name: "Naâma", communes: ["Commune1", "Commune2"] },
  { code: "46", name: "Aïn Témouchent", communes: ["Commune1", "Commune2"] },
  { code: "47", name: "Ghardaïa", communes: ["Commune1", "Commune2"] },
  { code: "48", name: "Relizane", communes: ["Commune1", "Commune2"] },
  { code: "49", name: "El M'Ghair", communes: ["Commune1", "Commune2"] },
  { code: "50", name: "El Meniaa", communes: ["Commune1", "Commune2"] },
  { code: "51", name: "Ouled Djellal", communes: ["Commune1", "Commune2"] },
  { code: "52", name: "Bordj Baji Mokhtar", communes: ["Commune1", "Commune2"] },
  { code: "53", name: "Béni Abbès", communes: ["Commune1", "Commune2"] },
  { code: "54", name: "Timimoun", communes: ["Commune1", "Commune2"] },
  { code: "55", name: "Touggourt", communes: ["Commune1", "Commune2"] },
  { code: "56", name: "Djanet", communes: ["Commune1", "Commune2"] },
  { code: "57", name: "In Salah", communes: ["Commune1", "Commune2"] },
  { code: "58", name: "In Guezzam", communes: ["Commune1", "Commune2"] },
];

export const communesData = {/* ...communes data as provided... */};
