export interface Station {
  station_code: string;
  station_name: string;
}

export const stations: Station[] = [
  {"station_code": "01A", "station_name": "Adrar"},
  {"station_code": "02A", "station_name": "Chlef"},
  {"station_code": "03A", "station_name": "Laghouat"},
  {"station_code": "03B", "station_name": "Laghouat (Aflou)"},
  {"station_code": "04A", "station_name": "Oum El Bouaghi (Ain Mlila)"},
  {"station_code": "04B", "station_name": "Oum El Bouaghi"},
  {"station_code": "05A", "station_name": "Batna"},
  {"station_code": "05B", "station_name": "Batna (Barika)"},
  {"station_code": "06A", "station_name": "Bejaïa"},
  {"station_code": "06B", "station_name": "Bejaïa (Akbou)"},
  {"station_code": "07A", "station_name": "Biskra"},
  {"station_code": "08A", "station_name": "Béchar"},
  {"station_code": "09A", "station_name": "Blida"},
  {"station_code": "09B", "station_name": "Blida (Boufarik)"},
  {"station_code": "10A", "station_name": "Bouira"},
  {"station_code": "11A", "station_name": "Tamanrasset"},
  {"station_code": "12A", "station_name": "Tébessa"},
  {"station_code": "13A", "station_name": "Tlemcen"},
  {"station_code": "13B", "station_name": "Tlemcen (Maghnia)"},
  {"station_code": "14A", "station_name": "Tiaret"},
  {"station_code": "15A", "station_name": "Tizi Ouzou"},
  {"station_code": "15B", "station_name": "Tizi Ouzou (Azazga)"},
  {"station_code": "16A", "station_name": "Alger (Bir Mourad Rais)"},
  {"station_code": "16B", "station_name": "Alger (Bab Ezzouar)"},
  {"station_code": "16C", "station_name": "Alger (Chéraga)"},
  {"station_code": "16D", "station_name": "Alger (Reghaia)"},
  {"station_code": "16E", "station_name": "Alger (Centre - Sacré-Cœur)"},
  {"station_code": "16F", "station_name": "Alger (Baba Hassen)"},
  {"station_code": "16G", "station_name": "Alger (Baraki)"},
  {"station_code": "16H", "station_name": "Alger (Bab Ezzouar - Douzi)"},
  {"station_code": "17A", "station_name": "Djelfa"},
  {"station_code": "17B", "station_name": "Djelfa (Ain Ouassara)"},
  {"station_code": "18A", "station_name": "Jijel"},
  {"station_code": "19A", "station_name": "Sétif"},
  {"station_code": "19B", "station_name": "Sétif (El Eulma)"},
  {"station_code": "19C", "station_name": "Sétif (Ain Oulmene)"},
  {"station_code": "19RE", "station_name": "Sétif (Guidjel)"},
  {"station_code": "20A", "station_name": "Saïda"},
  {"station_code": "21A", "station_name": "Skikda"},
  {"station_code": "22A", "station_name": "Sidi Bel Abbès"},
  {"station_code": "23A", "station_name": "Annaba"},
  {"station_code": "23B", "station_name": "Annaba (El Bouni)"},
  {"station_code": "24A", "station_name": "Guelma"},
  {"station_code": "25A", "station_name": "Constantine (Zouaghi)"},
  {"station_code": "25B", "station_name": "Constantine (Ali Mendjeli)"},
  {"station_code": "25C", "station_name": "Constantine"},
  {"station_code": "26A", "station_name": "Médéa"},
  {"station_code": "27A", "station_name": "Mostaganem"},
  {"station_code": "28A", "station_name": "M'sila"},
  {"station_code": "28B", "station_name": "M'sila (Bousaada)"},
  {"station_code": "29A", "station_name": "Mascara (Mohammadia)"},
  {"station_code": "29B", "station_name": "Mascara (Ville)"},
  {"station_code": "30A", "station_name": "Ouargla"},
  {"station_code": "31A", "station_name": "Oran (Maraval)"},
  {"station_code": "31B", "station_name": "Oran (Bir El Djir)"},
  {"station_code": "31C", "station_name": "Oran (Gambetta)"},
  {"station_code": "32A", "station_name": "El Bayadh"},
  {"station_code": "33A", "station_name": "Illizi"},
  {"station_code": "34A", "station_name": "Bordj Bou Arreridj"},
  {"station_code": "35A", "station_name": "Boumerdès"},
  {"station_code": "35B", "station_name": "Boumerdès (Ouled Moussa)"},
  {"station_code": "36A", "station_name": "El Taref"},
  {"station_code": "37A", "station_name": "Tindouf"},
  {"station_code": "38A", "station_name": "Tissemsilt"},
  {"station_code": "39A", "station_name": "El Oued"},
  {"station_code": "40A", "station_name": "Khenchela"},
  {"station_code": "41A", "station_name": "Souk Ahras"},
  {"station_code": "42A", "station_name": "Tipaza"},
  {"station_code": "43A", "station_name": "Mila"},
  {"station_code": "43B", "station_name": "Mila (Chelghoum El Aid)"},
  {"station_code": "44A", "station_name": "Ain Defla"},
  {"station_code": "44B", "station_name": "Ain Defla (Khemis Miliana)"},
  {"station_code": "45A", "station_name": "Naâma (Mécheria)"},
  {"station_code": "46A", "station_name": "Aïn Témouchent"},
  {"station_code": "47A", "station_name": "Ghardaïa"},
  {"station_code": "48A", "station_name": "Relizane"},
  {"station_code": "49A", "station_name": "Timimoun"},
  {"station_code": "51A", "station_name": "Ouled Djellal"},
  {"station_code": "52A", "station_name": "Beni Abbès"},
  {"station_code": "53A", "station_name": "In Salah"},
  {"station_code": "55A", "station_name": "Touggourt"},
  {"station_code": "58A", "station_name": "El Meniaa"}
];
